// Code generated by goctl. DO NOT EDIT.
package types

type QueryReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type QueryResp struct {
	Book
	Message string `json:"message"`
}

type AddReq struct {
	Name string `json:"name"`
}

type AddResp struct {
	Message string `json:"message"`
}

type Book struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type DelReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type DelResp struct {
	Message string `json:"message"`
}

type UpdateReq struct {
	Book
}

type UpdateResp struct {
	Message string `json:"message"`
}

type GetAllReq struct {
}

type GetAllResp struct {
	Books []Book `json:"books"`
}
