// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"book/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/query",
				Handler: bookGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/add",
				Handler: bookAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/del",
				Handler: bookDelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/update",
				Handler: bookUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getAll",
				Handler: bookGetAllHandler(serverCtx),
			},
		},
	)
}
